name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12

        #provide the user, password and db name
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: mysecret
          POSTGRES_DB: simple_bank_three
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install golang-migrate
      run:  |
            curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.0/migrate.darwin-amd64.tar.gz | tar xvz
            sudo mv migrate /usr/local/bin/migrate
            which migrate
        
    - name: Run migrations 
      run: make migrateup

    - name: Test
      run: make test
